/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mhjuice_management;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author asus
 */
public class frm_pemilik extends javax.swing.JFrame {

    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();
    
    /**
     * Creates new form frm_pemilik
     */
    public frm_pemilik() {
        initComponents();
        k.connect();

    }
    
public void exportToPDF() {
    try {
        String path = System.getProperty("user.home") + "\\Downloads\\laporan_penjualan.pdf";

        String sql = "SELECT jus.nama_jus, jus.tanggal, pengguna.nama_pengguna, daftar_jus.harga " +
                     "FROM jus " +
                     "JOIN daftar_jus ON jus.nama_jus = daftar_jus.nama_jus " +
                     "JOIN pengguna ON jus.id_petugas = pengguna.id_pengguna " +
                     "WHERE jus.tanggal >= DATE_SUB(CURDATE(), INTERVAL 30 DAY)";

        PreparedStatement ps = k.getCon().prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream(path));
        document.open();

        document.add(new Paragraph("LAPORAN PENJUALAN MH JUICE"));
        document.add(new Paragraph(" "));

        PdfPTable table = new PdfPTable(4);
        table.addCell("Tanggal");
        table.addCell("Nama Jus");
        table.addCell("Nama Petugas");
        table.addCell("Harga");

        int totalHarga = 0;

        while (rs.next()) {
            table.addCell(rs.getString("tanggal"));
            table.addCell(rs.getString("nama_jus"));
            table.addCell(rs.getString("nama_pengguna"));
            int harga = rs.getInt("harga");
            table.addCell(String.valueOf(harga));
            totalHarga += harga;
        }

        // Tambah baris kosong pemisah
        PdfPCell emptyCell = new PdfPCell(new Paragraph(" "));
        emptyCell.setColspan(4);
        emptyCell.setBorder(0);
        table.addCell(emptyCell);

        // Tambahkan baris total
        table.addCell("");
        table.addCell("");
        table.addCell("TOTAL");
        table.addCell(String.valueOf(totalHarga));

        document.add(table);
        document.close();

        JOptionPane.showMessageDialog(null, "Laporan berhasil diunduh sebagai PDF!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal mengekspor PDF: " + e.getMessage());
    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_jus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        btn_petugas1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MH FRESH JUICE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        btn_jus.setBackground(new java.awt.Color(204, 204, 204));
        btn_jus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mhjuice_management/Jus.png"))); // NOI18N
        btn_jus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_jus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_jus, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 270, 280));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UNDUH CATATAN PENJUALAN 30 HARI TERAKHIR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 450, 40));

        jButton4.setBackground(new java.awt.Color(102, 204, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("UNDUH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 170, 60));

        btn_keluar.setBackground(new java.awt.Color(102, 204, 255));
        btn_keluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_keluar.setForeground(new java.awt.Color(255, 255, 255));
        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 120, 30));

        btn_petugas1.setBackground(new java.awt.Color(204, 204, 204));
        btn_petugas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mhjuice_management/Petugas.png"))); // NOI18N
        btn_petugas1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_petugas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_petugas1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_petugas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 270, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_jusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jusActionPerformed
        // TODO add your handling code here:
        frm_pemilik2 frm_jus = new frm_pemilik2();
        frm_jus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_jusActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        exportToPDF();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        frm_login frm = new frm_login();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_petugas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_petugas1ActionPerformed
        // TODO add your handling code here:
        frm_pemilik1 frm1 = new frm_pemilik1();
        frm1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_petugas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_pemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_pemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_pemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_pemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_pemilik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_jus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_petugas1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
