/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mhjuice_management;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JTextField;

/**
 *
 * @author asus
 */
public class frm_pemilik1 extends javax.swing.JFrame {

    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();
//    Untuk Proses Edit
boolean addMode = false;
boolean editMode = false;
String idPetugasEdit = "";

    
    /**
     * Creates new form frm_pemilik1
     */
    public frm_pemilik1() {
        initComponents();
        k.connect();
        
        //Warna Tabel Petugas
        tabel_petugas.setBackground(Color.WHITE);
        tabel_petugas.setForeground(Color.BLACK);
        tabel_petugas.getTableHeader().setBackground(new Color(220, 220, 220));
        tabel_petugas.getTableHeader().setForeground(Color.BLACK);
        tabel_petugas.setRowHeight(25);
        
        //Warna TextField Atas
        text_petugas1.setBackground(Color.WHITE);
//        text_password.setForeground(Color.BLACK);
        
        //Warna TextField Bawah
        text_petugas2.setBackground(Color.WHITE);
        text_password1.setForeground(Color.BLACK);
        
        //Warna TextField ID
        text_id.setBackground(Color.WHITE);
        text_id.setForeground(Color.BLACK);
        
        
        
        
        refreshTable();
//    Nama Text 
    setPlaceholder(text_petugas1, "Nama Petugas...");
    setPlaceholder(text_password1, "Password...");
    
//    Text field Monaktif semua
    text_petugas1.setEnabled(false);
    text_password1.setEnabled(false);
    text_petugas2.setEnabled(false);
    text_password2.setEnabled(false);
    }

public void refreshTable() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Petugas");
    model.addColumn("Nama Petugas");
    model.addColumn("Password");

    tabel_petugas.setModel(model);

    try {
        String sql = "SELECT id_pengguna, nama_pengguna, kata_sandi FROM pengguna WHERE tugas = 1";
        PreparedStatement stat = k.getCon().prepareStatement(sql);
        ResultSet rs = stat.executeQuery();

        while (rs.next()) {
            Object[] data = {
                rs.getInt("id_pengguna"),
                rs.getString("nama_pengguna"),
                rs.getString("kata_sandi")
            };
            model.addRow(data);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "SQL Error: " + e.getMessage());
    }
}

     
          private void setPlaceholder(JTextField field, String placeholder) {
    field.setText(placeholder);
    field.setForeground(Color.GRAY);

    field.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (field.getText().equals(placeholder)) {
                field.setText("");
                field.setForeground(Color.BLACK);
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (field.getText().trim().equals("")) {
                field.setText(placeholder);
                field.setForeground(Color.GRAY);
            }
        }
    });
}

     private void bersihkanField() {
    setPlaceholder(text_petugas1, "Nama Petugas...");
    setPlaceholder(text_password1, "Password...");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        text_id = new javax.swing.JTextField();
        btn_keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_petugas = new javax.swing.JTable();
        btn_hapus = new javax.swing.JButton();
        text_petugas1 = new javax.swing.JTextField();
        text_password1 = new javax.swing.JTextField();
        text_password2 = new javax.swing.JTextField();
        text_petugas2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        text_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_id.setForeground(new java.awt.Color(153, 153, 153));
        text_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_idActionPerformed(evt);
            }
        });
        jPanel1.add(text_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 90, 30));

        btn_keluar.setBackground(new java.awt.Color(102, 204, 255));
        btn_keluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_keluar.setForeground(new java.awt.Color(255, 255, 255));
        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 120, 30));

        tabel_petugas.setBackground(new java.awt.Color(204, 204, 204));
        tabel_petugas.setForeground(new java.awt.Color(255, 255, 255));
        tabel_petugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Petugas", "Nama Petugas", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_petugas.setGridColor(new java.awt.Color(0, 0, 0));
        tabel_petugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_petugasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_petugas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 900, 330));

        btn_hapus.setBackground(new java.awt.Color(255, 51, 51));
        btn_hapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("Hapus");
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 590, 120, 30));

        text_petugas1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_petugas1.setForeground(new java.awt.Color(153, 153, 153));
        text_petugas1.setText("Nama Petugas...");
        text_petugas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_petugas1ActionPerformed(evt);
            }
        });
        jPanel1.add(text_petugas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 240, 30));

        text_password1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_password1.setForeground(new java.awt.Color(153, 153, 153));
        text_password1.setText("Password...");
        text_password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_password1ActionPerformed(evt);
            }
        });
        jPanel1.add(text_password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 240, 30));

        text_password2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_password2.setForeground(new java.awt.Color(153, 153, 153));
        text_password2.setText("Password...");
        text_password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_password2ActionPerformed(evt);
            }
        });
        jPanel1.add(text_password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 240, 30));

        text_petugas2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_petugas2.setForeground(new java.awt.Color(153, 153, 153));
        text_petugas2.setText("Nama Petugas...");
        text_petugas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_petugas2ActionPerformed(evt);
            }
        });
        jPanel1.add(text_petugas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 240, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MH FRESH JUICE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        btn_tambah.setBackground(new java.awt.Color(102, 204, 255));
        btn_tambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 120, 30));

        btn_simpan.setBackground(new java.awt.Color(102, 204, 255));
        btn_simpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 590, 120, 30));

        btn_edit.setBackground(new java.awt.Color(102, 204, 255));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_idActionPerformed

    private void text_petugas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_petugas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_petugas1ActionPerformed

    private void text_password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_password1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_password1ActionPerformed

    private void text_password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_password2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_password2ActionPerformed

    private void text_petugas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_petugas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_petugas2ActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        frm_pemilik frm = new frm_pemilik();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
    addMode = true;
    editMode = false;

    text_petugas1.setEnabled(true);
    text_password1.setEnabled(true);
    text_petugas2.setEnabled(false);
    text_password2.setEnabled(false);
    bersihkanField();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
       try {
    if (addMode) {
        // ===== TAMBAH DATA =====
        String namaPetugas = text_petugas1.getText().trim();
        String password = text_password1.getText().trim();

        if (namaPetugas.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Semua field harus diisi!");
            return;
        }

        // Cek duplikasi nama_petugas
        String cekSql = "SELECT COUNT(*) FROM pengguna WHERE nama_pengguna = ? AND tugas = 1";
        PreparedStatement cekStat = k.getCon().prepareStatement(cekSql);
        cekStat.setString(1, namaPetugas);
        ResultSet rsCek = cekStat.executeQuery();
        rsCek.next();
        int count = rsCek.getInt(1);

        if (count > 0) {
            JOptionPane.showMessageDialog(null, "Nama petugas sudah ada. Silakan gunakan nama lain.");
            return;
        }

        String sql = "INSERT INTO pengguna (nama_pengguna, kata_sandi, tugas) VALUES (?, ?, ?)";
        PreparedStatement stat = k.getCon().prepareStatement(sql);
        stat.setString(1, namaPetugas);
        stat.setString(2, password);
        stat.setInt(3, 1); // tugas = 1 (petugas)
        stat.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data petugas berhasil ditambahkan!");

        bersihkanField();
        text_petugas1.setEnabled(false);
        text_password1.setEnabled(false);

    } else if (editMode) {
        // ===== EDIT DATA =====
        String namaBaru = text_petugas2.getText().trim();
        String passwordBaru = text_password2.getText().trim();

        if (namaBaru.isEmpty() || passwordBaru.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Semua field harus diisi!");
            return;
        }

        String sql = "UPDATE pengguna SET nama_pengguna = ?, kata_sandi = ? WHERE id_pengguna = ?";
        PreparedStatement stat = k.getCon().prepareStatement(sql);
        stat.setString(1, namaBaru);
        stat.setString(2, passwordBaru);
        stat.setString(3, idPetugasEdit);
        stat.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data petugas berhasil diupdate!");

        bersihkanField();
        text_petugas2.setEnabled(false);
        text_password2.setEnabled(false);
    }

    refreshTable();

    // Reset mode
    addMode = false;
    editMode = false;

} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "SQL Error: " + e.getMessage());
}

    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
     editMode = true;
     addMode = false;
    text_petugas2.setEnabled(true);
    text_password2.setEnabled(true);
    
      // textfield atas Monaktif Bun
    text_petugas1.setEnabled(false);
    text_password1.setEnabled(false); 
        
        
    }//GEN-LAST:event_btn_editActionPerformed

    private void tabel_petugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_petugasMouseClicked
        // TODO add your handling code here:
int baris = tabel_petugas.getSelectedRow();
    if (baris != -1) {
        String idPetugas = tabel_petugas.getValueAt(baris, 0).toString();
        String namaPetugas = tabel_petugas.getValueAt(baris, 1).toString();
        String password = tabel_petugas.getValueAt(baris, 2).toString();

        // Set ke textfield
        text_id.setText(idPetugas); // ID
        text_petugas2.setText(namaPetugas); // Nama
        text_password2.setText(password);   // Password

        // Aktifkan field edit
        text_petugas2.setEnabled(true);
        text_password2.setEnabled(true);

        // Simpan untuk keperluan update
        idPetugasEdit = idPetugas;
    }
        
    }//GEN-LAST:event_tabel_petugasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_pemilik1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_pemilik1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_pemilik1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_pemilik1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_pemilik1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_petugas;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField text_password1;
    private javax.swing.JTextField text_password2;
    private javax.swing.JTextField text_petugas1;
    private javax.swing.JTextField text_petugas2;
    // End of variables declaration//GEN-END:variables
}
